<?php

use Illuminate\Database\Seeder;
use App\Employee;

class EmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $rows = [
                ["FRCSE007","Gloria"],
                ["FSEC037","Tennyson Anchilo"],
                ["FSEC076","Aran Vigneshwaran"],
                ["FSEC084","Mounika"],
                ["FSEC058","Radhakrishnan"],
                ["FALB 036","Parvathy"],
                ["ABCRAK009","Sheikh Peer"],
                ["FSEC062","Akhil"],
                ["FSEC085","Siju Varghese"],
                ["","Wasim Akram"],
                ["","Musthaq"],
                ["No visa","Mohammad Aslam"],
                ["No visa","Jayaraj - Graphic Designer"],
                ["FALB 029","Zar Muhammed-Driver"],
                ["FALB 035","Nadeem-Driver"],
                ["FSEC077","Rohullah Khan-Driver"],
                ["","Muhammed Dar Gul - Driver"],
                ["FSEC002","Abdul Lathif-Driver"],
                ["FSEC004","Ali Hassan-Driver"],
                ["FRCSE019","Riyat Khan-Driver"],
                ["FALB 021","ABDUL SATTAR-Driver"],
                ["ABCAJM019","Syed Umar-Driver"],
                ["ABCAJM005","Hikmat-Driver"],
                ["FRCSE017","Noor - Driver"],
                ["No visa","Abhidullah"],
                ["FALB 067","AmalRaj"],
                ["","Sheik Sathar"],
                ["FRCSE020","Riaz Khan-Driver"],
                ["","Saidullah"],
                ["","Praveen Muthalagu"],
                ["FRCSE015","Muthuvel Prabhu"],
                ["FRCSE032","Ajmal Kabeer"],
                ["FSEC034","Sivachidambaram"],
                ["FSEC010","Jayaraj"],
                ["FSEC072","Sandeep Ponnappan"],
                ["FSEC069","Abbas Muhammed"],
                ["FSEC073","BAKKIYARAJ SELVAM"],
                ["FSEC075","ANANTHAKRISHNAN"],
                ["FSS011","Rafeeq"],
                ["FSS015","Ramkumar"],
                ["FSEC078","Satham Hussain"],
                ["","Vijay Prasad"],
                ["No visa","Sarath"],
                ["No visa","Pranitha Tammina"],
                ["FSEC071","Satyawan Singh"],
                ["","Mohammad Kashif Raza"],
                ["","Shakir Iqbal"],
                ["FRCSE013","Muhammad Ajmal"],
                ["FRCSE031","Waqas"],
                ["FRCSE022","Sandeep"],
                ["FRCSE005","Baljith Singh"],
                ["FRCSE021","Sajithlal"],
                ["FRCSE027","Shahid Mehmood"],
                ["FRCSE028","Thoufeekh"],
                ["FRCSE033","Vishnu Mohan"],
                ["FSEC019","MUHAMMAD USMAN"],
                ["FSEC022","Nizar Nazer"],
                ["FSEC024","Rahul Manhas"],
                ["FSEC018","MUHAMMAD TAUSEEF"],
                ["FSEC023","Periyasamy"],
                ["FSEC035","Srinivasa Rao"],
                ["FSEC006","Ghulam Musthafa"],
                ["FSEC031","Shafaat"],
                ["FSEC036","Suheel Kumar"],
                ["FSEC039","Vetrivel"],
                ["FSEC042","Vignesh Prabhu"],
                ["FSEC045","Ram Sagar"],
                ["FSEC055","Sathyaraj"],
                ["FSEC054","Khizar Hayat"],
                ["FSEC065","Naven"],
                ["FSEC059","Amit Kumar"],
                ["FSEC064","SIJO"],
                ["FSEC060","Benchmin"],
                ["FSEC066","SHAHRUKH S. KHAN"],
                ["FSEC068","Rajab Hussain"],
                ["FSEC070","Chris Riyaan"],
                ["FSEC074","Mohammad Intasar"],
                ["FSS008","SHIYAS LATHEEF"],
                ["FSS001","Abhilash Asokan"],
                ["FSS006","Mohasin"],
                ["FSS003","Ishtiq"],
                ["FSS010","Latheesh Mohan"],
                ["FSS014","Sujit"],
                ["FSS016","ALI RAZA"],
                ["FSS017","Shibin"],
                ["ABCAJM014","Renjith"],
                ["ABCAJM017","Shafeeq"],
                ["ABCAJM009","Midhun Muralee"],
                ["FALB 011","Mahin"],
                ["FALB 041","INDRAJEET"],
                ["ABCRAK012","Zahid "],
                ["ABCRAK014","Zulfiqar Ali"],
                ["","Dharmendra Yadav"],
                ["No visa","Vinod Kumar"],
                ["No visa","Shivesh Mohan"],
                ["FSEC025","RAISU ALEX"],
                ["FALB 008","Riyas"],
                ["FALB 025","Mujahid"],
                ["FALB 055","Rabin Anish"],
                ["FALB 059","Janurie Lasala"],
                ["FALG 002","Anoop"],
                ["FALG 003","Nabin Paudel"],
                ["FALG 004","Prajeesh"],
                ["FALG 005","SHABANA"],
                ["","Megha Suresh"],
                ["FSEC038","Tisha Thomas"],
                ["","Rajimon Nellippallil"],
                ["ABCAJM003","Asmathulla"],
                ["ABCAJM016","Saidullah"],
                ["ABCAJM023","Ishan Javeed"],
                ["ABCAJM025","Kiran Kumar"],
                ["ABCAJM024","MUHAMMAD HAMZA"],
                ["FALB 004","Mohammed Razzudin"],
                ["FALB 005","Mubassir Kolathur"],
                ["FALB 010","Yasir Aslam"],
                ["FALB 016","Munsab Ali"],
                ["FALB 002","Ghulam Murthuza"],
                ["FALB 013","Ansar Ali"],
                ["FALB 024","Shabbir"],
                ["FALB 027","Abdul Rehman"],
                ["FALB 032","JITHIN PUTHALATH"],
                ["FALB 037","Ananthanarayanan "],
                ["FALB 040","Arifullah"],
                ["FALB 042","Sabidullah"],
                ["FALB 044","SOHAIL ZAFAR"],
                ["FALB 047","Mushfique K"],
                ["FALB 051","Syed Azeezullah Hussain"],
                ["FALB 049","Jerry Prakash"],
                ["FALB 052","WAJAITH ALI"],
                ["FALB 053","ALEENA RAISU"],
                ["FALB 054","Ivette mofuayi ntambue"],
                ["FALB 056","Muhammad Ashik"],
                ["FALB 057","Hareesh"],
                ["FALB 060","Suman S "],
                ["FALB 062","RAHUL"],
                ["FALB 063","Sukhraj Singh"],
                ["FALB 064","Anbu Selvan "],
                ["FALB 065","Jiril Georage"],
                ["FALB 066","Babul kumar"],
                ["FALB 067","Vikram kumar"],
                ["FALB 068","Naeem"],
                ["FALB 069","Brighten Antony"],
                ["FALB 070","Albowsal"],
                ["FALB 071","Neelamber"],
                ["FALB 072","Subin Vazhungal"],
                ["ABCRAK002","G.Bobi"],
                ["ABCRAK020","Kamal MIAH"],
                ["ABCRAK022","SYED  SAGHAR"],
                ["","Mustaqin"],
                ["FSEC079","Dharmendra Takur"],
                ["","Patil"],
                ["FALB 031","Rajesh"],
                ["","Nijo Joseph"],
                ["","SOORYADEV BIJU"],
                ["","Sibin"],
                ["","Bijeesh"],
                ["","Rana Ali Akbar"],
                ["","Farukh Toor"],
                ["","Sharavan Sasi Kumar"],
                ["","Rana Muneeb"],
                ["","Al Rasim"],
                ["","Lakweer Singh"],
                ["","Noor Rehman"],
                ["","Umer Khan"],
                ["","Shahul Hameed"],
                ["","Rohit"]
                ]; 

        $i = 0;
        foreach($rows as $row)
        {
            if(!$row[0])
                $row[0] = 'NO_EMPLOYEE_ID_'.$i;
            Employee::firstOrCreate([
                'name'=>$row[1],
                'employee_id'=>$row[0],
            ]);
        }
    }
}
