@extends('layouts.app')

@section('page-title', 'General Configuration')

@section('content')
<div class="container-fluid pt-2">

    @if (session('status'))
        <div class="alert alert-success mb-4" role="alert">
            {{ session('status') }}
        </div>
    @endif

    <div class="row">
        <div class="col-md-8 col-lg-6">
            <div class="card-white p-4">
                <form action="{{ url('admin/settings/general') }}" method="post">
                    @csrf
                    @foreach($rows as $row)
                    <div class="form-group mb-4">
                        <label class="font-weight-bold text-dark">{{$row->label}}</label>
                        <input type='text' class="form-control" style="background-color: #f8fafc; border: 1px solid #e5e7eb; font-size: 0.95rem; padding: 0.75rem 1rem;" 
                            name='val[{{$row->id}}]' value='{{$row->val}}' />
                    </div>
                    @endforeach
                    <div class="mt-4 border-top pt-4 text-right">
                        <a href="{{ url('admin/settings') }}" class="btn ui-btn btn-light border mr-2">Cancel</a>
                        <button type="submit" class="btn ui-btn ui-btn-primary px-4">
                            <i class="fas fa-save mr-2"></i> Save Changes
                        </button>
                    </div>
                </form>
            </div>

            <!-- System Maintenance Card -->
            <div class="card-white p-4 mt-4">
                <h5 class="font-weight-bold text-dark mb-3"><i class="fas fa-broom mr-2 text-primary"></i>System Maintenance</h5>
                <p class="text-muted small mb-3">Clear temporary files generated by system reports (like large Excel exports) to free up disk space.</p>
                <form action="{{ url('admin/settings/clear-excel-cache') }}" method="post" onsubmit="return confirm('Are you sure you want to clear the temporary report cache? This will not delete any actual data.')">
                    @csrf
                    <button type="submit" class="btn btn-warning shadow-sm">
                        <i class="fas fa-trash-alt mr-2"></i> Clear Report Cache
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection
